import React, { useState, useEffect } from 'react';
import dynamic from 'next/dynamic';
import { NextSeo } from 'next-seo';
import Head from 'next/head';



const HomePage = dynamic(() => import('components/ui/SelfGrowthPart'), {
  ssr: false,
});


function Home() {
  const baseUrl = 'https://zo.live';
  const pageUrl = `${baseUrl}`;
  const finalThumbnail = "https://together-web-assets.s3.ap-south-1.amazonaws.com/zolivesvg.svg";
  const name = "World’s best daily self growth AI companion.";
  const description = "Create and Discover AI Content"

  const keywords = [
    'AI Content Generation',
    'Content Creation Tools',
    'AI Trivia',
    'Audiobook',
    'AI Narrated Books',
    'Personalized Audiobook Experience',
    'Automated Content',
    'AI Generated Comics',
    'Comic Books',
    'AI Quest Maker',
    'AI Video Creation',
    'Personalized Video Content',
    'Shorts',
    'Reels',
    'Trivia for Users',
    'Personalized Quests',
    'Article Generator',
    'AI Quiz Creator',
    'Natural Language Processing',
    'Content Automation',
    'Content Personalization',
    'Content Generation Platform',
  ];
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "name": name, // Name of the homepage or site
    "description": "Explore all features of our AI-driven platform for content generation. From AI-generated videos and trivia to interactive quests and rewards, we bring automation and creativity together.", // Description of the home page
    "thumbnailUrl": finalThumbnail, // Thumbnail image for the homepage (optional)
    "uploadDate": new Date().toISOString(),
    "contentUrl": pageUrl,       // URL to the homepage
    "author": {
      "@type": "Organization",
      "name": "Zo.live",  // Organization behind the platform
      "url": baseUrl      // URL to the organization's homepage
    },
    "publisher": {
      "@type": "Organization",
      "name": "Zo.live", // Publisher of the website
      "url": baseUrl    // URL to the publisher's website
    },
    "mainEntityOfPage": pageUrl,  // URL of the homepage
    "keywords": keywords, // SEO-friendly keywords
    "genre": "Content Generation", // Genre/category of content provided on the website
    "inLanguage": "en",            // Language of the page (default is English)
    "datePublished": new Date().toISOString(),
    "keywords": keywords,
    "features": [
      {
        "@type": "Shorts & Reels",
        "name": "AI-Generated Shorts",
        "description": "Watch a collection of AI-generated video shorts or reels, featuring a variety of genres and topics.",
        "keywords": "AI-generated videos, video shorts, AI reels"
      },
      {
        "@type": "Quests",
        "name": "AI-Generated Quests",
        "description": "Embark on quests designed by AI, solving challenges and earning rewards as you progress.",
        "keywords": "AI quests, interactive challenges, gamified experiences"
      },
      {
        "@type": "Trivia",
        "name": "AI Trivia",
        "description": "Engage in exciting and thought-provoking trivia challenges generated by AI to test your knowledge.",
        "keywords": "AI trivia, trivia challenges, knowledge test"
      },
      {
        "@type": "AudioBook",
        "name": "Audio Stories",
        "description": "Listen to immersive AI-generated audio stories across a wide range of genres and themes.",
        "keywords": "AI audio stories, immersive audio, storytelling, AI-generated stories"
      }
    ]
  };


  return (
    <>
      <NextSeo
        defaultTitle="Zo | AI Enabled Content Creation"
        title={name}
        description={description}
        canonical={pageUrl}
        url={pageUrl}
        openGraph={{
          url: pageUrl,
          title: `${name}`,
          description: description,
          site_name: 'Zo.live',
          images: [
            {
              url: finalThumbnail,
              width: 800,
              height: 600,
              alt: name,
              type: 'image/jpeg',
            }
          ],
        }}
        twitter={{
          handle: '@Zo_live',
          site: '@Zo_live',
          cardType: 'summary_large_image',
        }}
        additionalMetaTags={[
          {
            name: 'keywords',
            content: keywords
          },
          {
            name: 'twitter:title',
            content: name,
          },
          {
            name: 'twitter:description',
            content: description,
          },
          {
            name: 'twitter:image',
            content: finalThumbnail
          },
          {
            property: 'og:type',
            content: 'website'
          },
          {
            property: 'og:title',
            content: name,
          },
          {
            property: 'og:description',
            content: description,
          },
          {
            property: 'og:image',
            content: finalThumbnail,
          },
          {
            property: 'og:image:alt',
            content: `A preview of AI-powered content creation tools and features`
          },
          {
            property: 'og:site_name',
            content: 'Zo.live'
          },
          {
            property: 'og:url',
            content: pageUrl// Assuming you're in a browser context and want the current page URL
          },
        ]}

      />
      <Head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="format-detection" content="telephone=no" />
      </Head>
      <main><HomePage /></main>
    </>
  );
}

export default Home;