import React from 'react';
import dynamic from 'next/dynamic';
import { NextSeo } from 'next-seo';
import Head from 'next/head';

const ShortVideos = dynamic(
  () => import('components/ui/ShortVideoAll'),
  { ssr: false }
);

const shorts = () => {
  const baseUrl = 'https://zo.live';
  const pageUrl = `${baseUrl}/shorts`;
  const finalThumbnail = "https://together-web-assets.s3.ap-south-1.amazonaws.com/zolivesvg.svg";
  const name = "Shorts & Reels";
  const description = "Explore trending AI-generated shorts and reels, featuring creative and viral video clips powered by artificial intelligence."

  const keywords = [
    "AI Shorts",
    "AI-Generated Videos",
    "AI Reels",
    "AI-Powered Content",
    "Video Reels",
    "Short Video Content",
    "AI Animation",
    "Trending AI Videos",
    "AI Video Editing",
    "Video Clips",
    "Creative Videos",
    "Short Form Content",
    "Viral Shorts",
    "Video Editing",
    "Social Media Reels",
    "Content Creation"
  ].join(', ');

  const structuredData = {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    "name": "AI-Generated Shorts", // Title of the shorts page
    "description": "Explore a collection of AI-generated shorts. Watch videos crafted by AI to entertain and inform.", // Description of the page
    "thumbnailUrl": finalThumbnail, // URL to the thumbnail image for the collection
    "uploadDate": new Date().toISOString(),
    "contentUrl": pageUrl,       // URL to the shorts collection page
    "author": {
      "@type": "Organization",
      "name": "Zo.live",  // Name of the organization creating or hosting the shorts
      "url": baseUrl      // URL to the organization's homepage
    },
    "publisher": {
      "@type": "Organization",
      "name": "Zo.live", // Name of the publisher
      "url": baseUrl    // URL to the publisher's website
    },
    "mainEntityOfPage": pageUrl,  // URL of the shorts collection page
    "keywords": "AI-generated, shorts, reels, videos, AI, entertainment", // SEO-friendly keywords for shorts
    "genre": "Video",            // Genre or category of content (could be 'AI-generated', 'Shorts', etc.)
    "inLanguage": "en",          // Language of the content
    "datePublished": new Date().toISOString(),
    "video": [
      {
        "@type": "VideoObject",
        "name": name,       // Title of the individual short
        "description": description, // Short description of the video
        "thumbnailUrl": finalThumbnail, // URL to the thumbnail of the short
        "uploadDate": new Date().toISOString(),
        "contentUrl": pageUrl, // URL to the video file or page
        "duration": "PT1M",        // Duration of the short (example: 1 minute)
        "publisher": {
          "@type": "Organization",
          "name": "Zo.live",     // Publisher of the individual short video
          "url": baseUrl         // URL to the publisher's website
        },
        "creator": {
          "@type": "Organization",
          "name": "Zo.live",     // Creator of the short video (if AI-generated by Zo.live)
          "url": baseUrl         // URL to the creator's website
        },
        "mainEntityOfPage": pageUrl, // URL to the page or video
        "keywords": keywords        // Keywords related to the specific short
      }
    ]
  };


  return (
    <>
      <NextSeo
        defaultTitle="Zo | AI Enabled Content Creation"
        title={`${name} | Zo.live`}
        description={description}
        canonical={pageUrl}
        url={pageUrl}
        openGraph={{
          url: pageUrl,
          title: `${name} | Zo.live`,
          description: description,
          site_name: 'Zo.live',
          type: 'Video',
          images: [
            {
              url: finalThumbnail,
              width: 800,
              height: 600,
              alt: name,
              type: 'image/jpeg',
            }
          ],
        }}
        twitter={{
          handle: '@Zo_live',
          site: '@Zo_live',
          cardType: 'summary_large_image',
        }}
        additionalMetaTags={[
          {
            name: 'keywords',
            content: 'AI-generated shorts, short videos, AI reels, creative shorts, video content'
          },
          {
            name: 'twitter:title',
            content:`${name} | Zo.live`
          },
          {
            name: 'twitter:description',
            content: description
          },
          {
            name: 'twitter:image',
            content: finalThumbnail // A generic thumbnail for the page or a featured short
          },
          {
            property: 'og:type',
            content: 'website'
          },
          {
            property: 'og:title',
            content: `${name} | Zo.live`
          },
          {
            property: 'og:description',
            content: description
          },
          {
            property: 'og:image',
            content: finalThumbnail
          },
          {
            property: 'og:image:alt',
            content: `A preview of the AI-generated short videos collection`
          },
          {
            property: 'og:site_name',
            content: 'Zo.live'
          },
          {
            property: 'og:url',
            content: pageUrl 
          },
        ]}


      />
      <Head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="format-detection" content="telephone=no" />
      </Head>
      <main>
      <ShortVideos />
      </main>
    </>
  );
};

export default shorts;
